# Generated by Django 3.2 on 2022-07-23 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BankAccount', '0003_customeraccount_bankname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
