# Generated by Django 3.2 on 2022-07-24 12:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankAccount', '0004_alter_bank_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccount',
            name='initialDepost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, null=True),
        ),
    ]
