# Generated by Django 3.2 on 2022-07-24 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BankAccount', '0005_customeraccount_initialdepost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeraccount',
            old_name='initialDepost',
            new_name='initialDeposit',
        ),
    ]
