# Generated by Django 3.2 on 2022-07-24 15:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankAccount', '0006_rename_initialdepost_customeraccount_initialdeposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='accountNumber',
            field=models.CharField(max_length=10, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
