# Generated by Django 3.2 on 2022-07-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankAccount', '0007_bank_accountnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='accountName',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
