# Generated by Django 3.2 on 2022-07-24 17:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankAccount', '0008_bank_accountname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransaction',
            name='accountNumber',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='beneficiaryAccountNumber',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
