# Generated by Django 3.2 on 2022-07-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankAccount', '0009_auto_20220724_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='accountName',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
