# Generated by Django 3.2 on 2022-07-25 12:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankAccount', '0010_alter_bank_accountname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='accountName',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='accountNumber',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
