# Generated by Django 3.2 on 2022-07-25 12:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankAccount', '0011_auto_20220725_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='accountNumber',
            field=models.CharField(max_length=10, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
