# Generated by Django 3.2 on 2022-07-26 11:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BankAccount', '0015_alter_bank_accountnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='narration',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='transactionDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bank',
            name='transactionType',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Withdrawal', 'Withdrawal')], max_length=200, null=True),
        ),
    ]
