# Generated by Django 3.2 on 2022-07-26 11:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankAccount', '0017_alter_bank_transactiontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=30),
        ),
    ]
