# Generated by Django 3.2 on 2022-07-26 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BankAccount', '0018_bank_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banktransaction',
            old_name='Amount',
            new_name='amount',
        ),
    ]
